export const navLinks = [
  { path: '/', label: 'Home', roles: ['installer'] },
  { path: '/appointments', label: 'Appointment Summary', roles: ['installer'] },
  { path: '/activity', label: 'Activity Summary', roles: ['installer'] },
  { path: '/ifi', label: 'IFI Dashboard', roles: ['installer'] },
  { path: '/installer/dashboard', label: 'Installer Dashboard', roles: ['installer'] },
  { path: '/install-manager/dashboard', label: 'Install Manager Dashboard', roles: ['admin', 'manager'] },
  { path: '/admin/dashboard', label: 'Admin Dashboard', roles: ['admin'] },
  { path: '/sales/dashboard', label: 'Sales Dashboard', roles: ['sales', 'manager', 'admin'] },
  { path: '/install-manager', label: 'Install Manager Dashboard', roles: ['admin', 'manager'] },
  { path: '/feedback', label: 'Feedback', roles: ['installer'] },
  { path: '/clients', label: 'Clients', roles: ['admin', 'manager'] },
  { path: '/crm/leads', label: 'Leads', roles: ['sales', 'manager', 'admin'] },
  { path: '/quotes', label: 'Quotes', roles: ['admin', 'manager'] },
  { path: '/invoices', label: 'Invoices', roles: ['admin', 'manager'] },
  { path: '/payments', label: 'Payments', roles: ['admin', 'manager'] },
  { path: '/messages', label: 'Messages', roles: ['admin', 'manager'] },
  { path: '/time-tracking', label: 'Time Tracking', roles: ['admin', 'manager'] },
  { path: '/reports', label: 'Reports', roles: ['admin', 'manager'] },
  { path: '/reports/technician-pay', label: 'Technician Pay', roles: ['admin', 'manager'] },
  { path: '#', label: 'MyLearning - SentientZone', roles: ['installer'] },
  { path: "/", label: "Home", roles: ["installer"] },
  { path: "/appointments", label: "Appointment Summary", roles: ["installer"] },
  { path: "/activity", label: "Activity Summary", roles: ["installer"] },
  { path: "/ifi", label: "IFI Dashboard", roles: ["installer"] },
  {
    path: "/installer/dashboard",
    label: "Installer Dashboard",
    roles: ["installer"],
  },
  {
    path: "/install-manager/dashboard",
    label: "Install Manager Dashboard",
    roles: ["admin", "manager"],
  },
  { path: "/manager/qa", label: "QA Dashboard", roles: ["manager", "admin"] },
  { path: "/admin/dashboard", label: "Admin Dashboard", roles: ["admin"] },
  {
    path: "/sales/dashboard",
    label: "Sales Dashboard",
    roles: ["sales", "manager", "admin"],
  },
  {
    path: "/install-manager",
    label: "Install Manager Dashboard",
    roles: ["admin", "manager"],
  },
  { path: "/feedback", label: "Feedback", roles: ["installer"] },
  { path: "/clients", label: "Clients", roles: ["admin", "manager"] },
  { path: "/crm/leads", label: "Leads", roles: ["sales", "manager", "admin"] },
  { path: "/quotes", label: "Quotes", roles: ["admin", "manager"] },
  { path: "/invoices", label: "Invoices", roles: ["admin", "manager"] },
  { path: "/payments", label: "Payments", roles: ["admin", "manager"] },
  { path: "/messages", label: "Messages", roles: ["admin", "manager"] },
  {
    path: "/time-tracking",
    label: "Time Tracking",
    roles: ["admin", "manager"],
  },
  { path: "/reports", label: "Reports", roles: ["admin", "manager"] },
  {
    path: "/admin/reports/payments",
    label: "Payment Reports",
    roles: ["admin", "finance"],
  },

  { path: "#", label: "MyLearning - SentientZone", roles: ["installer"] },
];
