export const navLinks = [
  { path: '/', label: 'Home', roles: ['Installer'] },
  { path: '/appointments', label: 'Appointment Summary', roles: ['Installer'] },
  { path: '/activity', label: 'Activity Summary', roles: ['Installer'] },
  { path: '/ifi', label: 'IFI Dashboard', roles: ['Installer'] },
  { path: '/install-manager', label: 'Install Manager Dashboard', roles: ['Admin', 'Manager'] },
  { path: '/install-manager/quotes/new', label: 'Create Quote', roles: ['Admin', 'Manager'] },
  { path: '/feedback', label: 'Feedback', roles: ['Installer'] },
  { path: '/clients', label: 'Clients', roles: ['Admin', 'Manager'] },
  { path: '/crm/leads', label: 'Leads', roles: ['Sales', 'Manager', 'Admin'] },
  { path: '/quotes', label: 'Quotes', roles: ['Admin', 'Manager'] },
  { path: '/invoices', label: 'Invoices', roles: ['Admin', 'Manager'] },
  { path: '/payments', label: 'Payments', roles: ['Admin', 'Manager'] },
  { path: '/messages', label: 'Messages', roles: ['Admin', 'Manager'] },
  { path: '/time-tracking', label: 'Time Tracking', roles: ['Admin', 'Manager'] },
  { path: '/reports', label: 'Reports', roles: ['Admin', 'Manager'] },
  { path: '#', label: 'MyLearning - SentientZone', roles: ['Installer'] },
];
