export const navLinks = [
  { path: '/', label: 'Home', roles: ['Installer'] },
  { path: '/appointments', label: 'Appointment Summary', roles: ['Installer'] },
  { path: '/activity', label: 'Activity Summary', roles: ['Installer'] },
  { path: '/ifi', label: 'IFI Dashboard', roles: ['Installer'] },
  { path: '/installer/dashboard', label: 'Installer Dashboard', roles: ['Installer'] },
  { path: '/install-manager/dashboard', label: 'Install Manager Dashboard', roles: ['Admin', 'Manager'] },
  { path: '/admin/dashboard', label: 'Admin Dashboard', roles: ['Admin'] },
  { path: '/sales/dashboard', label: 'Sales Dashboard', roles: ['Sales', 'Manager', 'Admin'] },
  { path: '/install-manager', label: 'Install Manager Dashboard', roles: ['Admin', 'Manager'] },
  { path: '/feedback', label: 'Feedback', roles: ['Installer'] },
  { path: '/clients', label: 'Clients', roles: ['Admin', 'Manager'] },
  { path: '/crm/leads', label: 'Leads', roles: ['Sales', 'Manager', 'Admin'] },
  { path: '/quotes', label: 'Quotes', roles: ['Admin', 'Manager'] },
  { path: '/invoices', label: 'Invoices', roles: ['Admin', 'Manager'] },
  { path: '/payments', label: 'Payments', roles: ['Admin', 'Manager'] },
  { path: '/messages', label: 'Messages', roles: ['Admin', 'Manager'] },
  { path: '/time-tracking', label: 'Time Tracking', roles: ['Admin', 'Manager'] },
  { path: '/reports', label: 'Reports', roles: ['Admin', 'Manager'] },
  { path: '/reports/technician-pay', label: 'Technician Pay', roles: ['Admin', 'Install Manager'] },
  { path: '#', label: 'MyLearning - SentientZone', roles: ['Installer'] },
  { path: "/", label: "Home", roles: ["Installer"] },
  { path: "/appointments", label: "Appointment Summary", roles: ["Installer"] },
  { path: "/activity", label: "Activity Summary", roles: ["Installer"] },
  { path: "/ifi", label: "IFI Dashboard", roles: ["Installer"] },
  {
    path: "/installer/dashboard",
    label: "Installer Dashboard",
    roles: ["Installer"],
  },
  {
    path: "/install-manager/dashboard",
    label: "Install Manager Dashboard",
    roles: ["Admin", "Manager"],
  },
  { path: "/manager/qa", label: "QA Dashboard", roles: ["Manager", "Admin"] },
  { path: "/admin/dashboard", label: "Admin Dashboard", roles: ["Admin"] },
  {
    path: "/sales/dashboard",
    label: "Sales Dashboard",
    roles: ["Sales", "Manager", "Admin"],
  },
  {
    path: "/install-manager",
    label: "Install Manager Dashboard",
    roles: ["Admin", "Manager"],
  },
  { path: "/feedback", label: "Feedback", roles: ["Installer"] },
  { path: "/clients", label: "Clients", roles: ["Admin", "Manager"] },
  { path: "/crm/leads", label: "Leads", roles: ["Sales", "Manager", "Admin"] },
  { path: "/quotes", label: "Quotes", roles: ["Admin", "Manager"] },
  { path: "/invoices", label: "Invoices", roles: ["Admin", "Manager"] },
  { path: "/payments", label: "Payments", roles: ["Admin", "Manager"] },
  { path: "/messages", label: "Messages", roles: ["Admin", "Manager"] },
  {
    path: "/time-tracking",
    label: "Time Tracking",
    roles: ["Admin", "Manager"],
  },
  { path: "/reports", label: "Reports", roles: ["Admin", "Manager"] },
  { path: "#", label: "MyLearning - SentientZone", roles: ["Installer"] },
];
